---
galaxy_info:
  author: Josh Santos <josh@omnidapps.com>
  description: Install common dependencies
  company: OmnidApps LLC
  license: license (GPLv2, CC-BY, etc)
  min_ansible_version: 1.2

  # platforms:
  # - name: Fedora
  #   versions:
  #   - all
  #   - 25
  # - name: SomePlatform
  #   versions:
  #   - all
  #   - 1.0
  #   - 7
  #   - 99.99
  galaxy_tags: []
  dependencies: []
